/*
Project: Artist Revenue Analysis
Author: Dominic Edebeatu
Dataset: Chinook */

--Identify the top 10 revenue-generating artists and rank them by total revenue.
-- Step 1: Calculate total revenue per artist
-- Revenue is computed as unit_price × quantity from invoice_line
WITH artist_revenue AS (
    SELECT 
        a.artist_id,                 -- Unique identifier for artist
        a.name AS artist,             -- Artist name
        SUM(i.unit_price * i.quantity) AS revenue  -- Total revenue per artist
    FROM invoice_line AS i
    INNER JOIN track AS t
        ON i.track_id = t.track_id    -- Link sales to tracks
    INNER JOIN album AS ab
        ON t.album_id = ab.album_id   -- Link tracks to albums
    INNER JOIN artist AS a
        ON ab.artist_id = a.artist_id -- Link albums to artists
    GROUP BY a.artist_id, a.name
)

-- Step 2: Rank artists by revenue and return top 10
SELECT
    artist_id,
    artist,
    revenue,
    RANK() OVER (ORDER BY revenue DESC) AS revenue_ranking
FROM artist_revenue
ORDER BY revenue DESC
LIMIT 10;

/*
Analyze artist performance by calculating total revenue, individual revenue
contribution, and cumulative revenue share to identify revenue concentration.
*/

-- Step 1: Aggregate total revenue per artist
-- Revenue is calculated as unit_price × quantity from invoice_line
WITH artist_revenue AS (
    SELECT 
        a.artist_id,                      -- Unique identifier for each artist
        a.name AS artist,                  -- Artist name
        SUM(i.unit_price * i.quantity) AS revenue  -- Total revenue generated by the artist
    FROM invoice_line i
    JOIN track t 
        ON i.track_id = t.track_id         -- Connect sales to tracks
    JOIN album ab 
        ON t.album_id = ab.album_id        -- Connect tracks to albums
    JOIN artist a 
        ON ab.artist_id = a.artist_id      -- Connect albums to artists
    GROUP BY a.artist_id, a.name
)

-- Step 2: Calculate running totals and revenue percentages
SELECT 
    artist, 
    revenue,

    -- Running total of revenue ordered from highest to lowest revenue
    -- artist_id is included to ensure deterministic ordering for ties
    SUM(revenue) OVER (
        ORDER BY revenue DESC, artist_id
    ) AS running_total,

    -- Percentage contribution of each artist to total revenue
    ROUND(
        revenue / SUM(revenue) OVER () * 100, 
        2
    ) AS percentage_revenue,

    -- Cumulative percentage of total revenue (Pareto analysis)
    ROUND(
        SUM(revenue) OVER (ORDER BY revenue DESC, artist_id)
        / SUM(revenue) OVER () * 100,
        2
    ) AS cumulative_pct
FROM artist_revenue
ORDER BY revenue DESC;


/*
Analyze the relationship between revenue generation (premium pricing)
and popularity (units sold) across artists.
*/

-- Step 1: Aggregate revenue and units sold per artist
-- Revenue is calculated as unit_price × quantity
-- Units sold represent total quantity purchased
WITH artist_revenue_unit AS (
    SELECT 
        a.artist_id,                             -- Unique artist identifier
        a.name AS artist,                        -- Artist name
        SUM(il.unit_price * il.quantity) AS revenue,   -- Total revenue per artist
        SUM(il.quantity) AS units_sold           -- Total units sold per artist
    FROM invoice_line il
    INNER JOIN track t 
        ON il.track_id = t.track_id              -- Connect sales to tracks
    INNER JOIN album ab 
        ON t.album_id = ab.album_id              -- Connect tracks to albums
    INNER JOIN artist a 
        ON ab.artist_id = a.artist_id            -- Connect albums to artists
    GROUP BY a.artist_id, a.name
)

-- Step 2: Rank each artist by revenue and by units sold
SELECT
    artist,
    revenue,
    units_sold,

    -- Rank artists by revenue (premium performance)
    RANK() OVER (ORDER BY revenue DESC) AS revenue_ranking,

    -- Rank artists by units sold (popularity)
    RANK() OVER (ORDER BY units_sold DESC) AS units_sold_ranking
FROM artist_revenue_unit
ORDER BY revenue DESC;
